---
- hosts: '{{swarm_master_address}}'
  become: yes
  become_method: sudo
  tasks:
    - name: Get the worker node token
      shell: 'docker swarm join-token worker -q'
      register: docker_worker_token  
    - debug: 
        var: docker_worker_token.stdout
    - debug:
        var: ansible_default_ipv4.address



    - name: add dummy host
      add_host:
        name: "token_holder"
        token: "{{ docker_worker_token.stdout }}"
        master_ip: "{{ ansible_default_ipv4.address }}" 
         



- hosts: '{{swarm_worker_address}}'
  become: yes
  become_method: sudo
  tasks:
    - name: Install necessary packages
      package:
        name: '{{item}}'
        state: present
      with_items:
        - wget
   

    - name: Get docker repository
      shell: 'wget https://download.docker.com/linux/centos/docker-ce.repo -O /etc/yum.repos.d/docker.repo'

    - name: install docker 
      package:
        name: docker-ce
        state: present

    - name: start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: 
      debug: 
        msg: "Token is {{ hostvars['token_holder']['token'] }} ip is {{ hostvars['token_holder']['master_ip'] }}"

    - name: Join worker to swarm
      shell: docker swarm join --token {{ hostvars['token_holder']['token'] }}  {{ hostvars['token_holder']['master_ip'] }}:2377
      
   

    




